$schema: https://json.schemastore.org/pre-commit-config.json
repos:
- repo: local
  hooks:
  - id: pre-commit
    name: lint
    language: system
    entry: make lint
    verbose: true
    stages: [ pre-commit ]
